//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FianzasApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caso
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public int CantidadImputados { get; set; }
        public System.DateTime FchUltActualizacion { get; set; }
        public decimal BalanceFianza { get; set; }
        public string Estado { get; set; }
    }
}
